---

- name: Redis | Load a variable file based on the OS type, or a default.
  ansible.builtin.include_vars: >
    {{ lookup('ansible.builtin.first_found', params) }}
  vars:
    params:
      files:
        - 'redis-{{ ansible_os_family | lower }}.yml'
      paths:
        - 'vars'
  tags:
    - install
    - redis_server

- name: Redis | Ensure Redis is installed.
  ansible.builtin.package:
    name: "{{ redis_packages }}"
    state: present
  tags:
    - install
    - redis_server

- name: Redis | Ensure Redis is running and enabled on boot.
  ansible.builtin.systemd:
    name: '{{ redis_service_name }}'
    state: started
    enabled: true
  tags:
    - install
    - redis_server
