---

- name: 'Prometheus nodejs | Restart node_exporter'
  ansible.builtin.systemd:
    daemon_reload: true
    name: 'node_exporter'
    state: 'restarted'
  when:
    - 'node_exporter_service_state != "stopped"'
    - 'ansible_service_mgr == "systemd"'
  become: true

- name: 'Prometheus nodejs | Restart node_exporter (init.d)'
  ansible.builtin.service:
    name: 'node_exporter'
    state: 'restarted'
  when:
    - 'node_exporter_service_state != "stopped"'
    - 'ansible_service_mgr != "systemd"'
  become: true

- name: 'Prometheus nodejs | Reload consul config'
  ansible.builtin.systemd:
    name: 'consul'
    state: 'reloaded'
  when: "'packer' not in group_names"
  become: true
