---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mysql_centos8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
  - name: mysql_debian11
    image: jrei/systemd-debian:11
    pre_build_image: true
    command: "/lib/systemd/systemd"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    platform: amd64
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
