---

- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Check for Python
      ansible.builtin.raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python if none
      ansible.builtin.raw: >
        test -e /usr/bin/apt &&
        (apt -y update && apt install -y python3-minimal) ||
        true  # We need to install on Debian-based only
      changed_when: false
      when: check_python.rc != 0

    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present
