---

- name: 'Atop | Run install as superuser'
  become: true
  block:

    - name: 'Atop | Install'
      ansible.builtin.package:
        name: 'atop'
        state: 'present'

    - name: 'Atop | Set collection interval'
      ansible.builtin.lineinfile:
        dest: '/etc/default/atop'
        regex: '"^(#)?LOGINTERVAL\s*='
        line: 'LOGINTERVAL={{ atop_interval_seconds }}'
      notify:
        - 'Atop | restart atop'
      register: 'atop_config_file'

    - name: 'Atop | Set service enabled flag'
      ansible.builtin.service:
        name: 'atop'
        enabled: true

    - name: 'Atop | Set service state'
      ansible.builtin.service:
        name: 'atop'
        state: '{{ "stopped" if "packer" in group_names else "started" }}'
      when: 'not atop_config_file is changed'
