---

- name: 'Check variables'
  ansible.builtin.include_tasks: 'check-vars.yml'

- name: 'Define os-specific vars'
  ansible.builtin.include_vars: '{{ ansible_os_family }}.yml'

- name: 'Define common vars'
  ansible.builtin.set_fact:
    beat_product: '{{ beat }}'
    conf_file: '{{ beats_conf_dir }}/{{ beat }}.yml'

- name: 'Install and configure - Linux'
  ansible.builtin.include_tasks: 'linux/main.yml'
  when: ansible_os_family != 'Windows'

- name: 'Install and configure - Windows'
  ansible.builtin.include_tasks: 'windows/main.yml'
  when: ansible_os_family == 'Windows'

- name: 'Force all notified handlers to run at this point'
  ansible.builtin.meta: 'flush_handlers'
