---

- name: Converge
  hosts: all

  # Deploy test sysemd unit files to test auto conf script
  pre_tasks:
    - name: 'Deploy example prometheus exporter systemd files'
      ansible.builtin.copy:
        src: '{{ item }}'
        dest: '/etc/systemd/system/'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop:
        - 'node_exporter.service'
        - 'prometheus-mysqld-exporter.service'

    - name: 'Enable Systemd services'
      ansible.builtin.systemd:
        name: '{{ item }}'
        enabled: true
        state: 'stopped'
      loop:
        - 'node_exporter.service'
        - 'prometheus-mysqld-exporter.service'

  tasks:
    - name: "Include vmagent"
      ansible.builtin.include_role:
        name: "vmagent"
