---

docker_key: 'https://download.docker.com/linux/debian/gpg'
docker_repo: 'deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable'
dependencies:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'gnupg2'
  - 'curl'
