---

docker_key: 'https://download.docker.com/linux/centos/gpg'
docker_repo: >-
  https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") |
  ternary("fedora", "centos") }}/docker-ce.repo
dependencies:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'gnupg2'
  - 'curl'
