---
galaxy_info:
  author: Alexander Shlygin <alexander.shlygin@aparavi.com>
  description: Aparavi app installer
  company: Aparavi AG

  min_ansible_version: 2.8.0

  license: BSD-3-Clause

  galaxy_tags: []

dependencies: []
