---
dependency:
  name: 'galaxy'
driver:
  name: 'docker'
platforms:
  - name: 'debian11'
    image: 'geerlingguy/docker-debian11-ansible'
    pre_build_image: true
    privileged: true
    platform: 'linux/amd64'
    command: ''
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: 'centos8'
    image: 'geerlingguy/docker-centos8-ansible'
    pre_build_image: true
    privileged: true
    platform: 'linux/amd64'
    command: ''
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: 'ubuntu2204'
    image: 'geerlingguy/docker-ubuntu2204-ansible'
    pre_build_image: true
    privileged: true
    platform: 'linux/amd64'
    command: ''
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
provisioner:
  name: 'ansible'
verifier:
  name: 'ansible'
