---

- name: Aparavi App | Create .dia secrets storage
  ansible.builtin.file:
    path: "/root/.dia"
    owner: root
    group: root
    state: directory
    mode: 0750
  when: app_secrets_config[app_type] | length > 0

- name: Aparavi App | Create secretsConfig.json
  ansible.builtin.copy:
    dest: "/root/.dia/secretsConfig.json"
    content: "{{ app_secrets_config[app_type] | to_nice_json }}"
    owner: root
    group: root
    mode: 0640
  when: app_secrets_config[app_type] | length > 0
