---

- name: 'Prometheus nodejs | Check Node Exporter service status'
  ansible.builtin.service:
    name: 'node_exporter'
    state: '{{ node_exporter_service_state }}'
    enabled: '{{ node_exporter_service_enabled }}'
