---

- name: 'Prometheus nodejs | Install | Install dependencies'
  ansible.builtin.package:
    name: '{{ node_exporter_custom.dependencies }}'
    state: 'present'

- name: 'Prometheus nodejs | Install | Create the node_exporter group'
  ansible.builtin.group:
    name: '{{ node_exporter_system_group }}'
    state: 'present'
    system: true

- name: 'Prometheus nodejs | Install | Create the node_exporter user'
  ansible.builtin.user:
    name: '{{ node_exporter_system_user }}'
    groups: '{{ node_exporter_system_group }}'
    append: true
    shell: '/usr/sbin/nologin'
    system: true
    createhome: false

- name: 'Prometheus nodejs | Install | Check installation'
  ansible.builtin.stat:
    path: '/usr/local/bin/node_exporter'
  register: '_installation'

- name: 'Prometheus nodejs | Installation block'
  check_mode: false
  when: 'not _installation.stat.exists or node_exporter_force_install'
  block:

    - name: 'Prometheus nodejs | Install | Create temporary directory'
      ansible.builtin.tempfile:
        state: 'directory'
      check_mode: false
      register: '_tmp_dir'

    - name: 'Prometheus nodejs | Install | Download node_exporter binary'
      ansible.builtin.get_url:
        url: '{{ node_exporter_tar_url }}'
        dest: >-
          {{ _tmp_dir.path }}/node_exporter-{{ node_exporter_version }}.linux-{{
            node_exporter_arch }}.tar.gz
        mode: '0666'
        owner: root
        group: root
      register: '_download_binary'
      until: '_download_binary is succeeded'
      retries: 5
      delay: 2

    - name: 'Prometheus nodejs | Install | Unpack node_exporter binary'
      ansible.builtin.unarchive:
        src: >-
          {{ _tmp_dir.path }}/node_exporter-{{ node_exporter_version }}.linux-{{
            node_exporter_arch }}.tar.gz
        dest: '{{ _tmp_dir.path }}'
        remote_src: true

    - name: 'Prometheus nodejs | Install | Propagate node_exporter binaries'
      ansible.builtin.copy:
        src: >-
          {{ _tmp_dir.path }}/node_exporter-{{ node_exporter_version }}.linux-{{
            node_exporter_arch }}/node_exporter
        dest: '/usr/local/bin/node_exporter'
        mode: '0750'
        owner: '{{ node_exporter_system_user }}'
        group: '{{ node_exporter_system_group }}'
        remote_src: true
      notify: 'Prometheus nodejs | Restart node_exporter'

  always:

    - name: 'Prometheus nodejs | Install | Remove Temp dir'
      ansible.builtin.file:
        path: '{{ _tmp_dir.path }}'
        state: 'absent'

- name: 'Prometheus nodejs | Install | Copy the Node Exporter systemd service'
  ansible.builtin.template:
    src: 'node_exporter.service.j2'
    dest: '/etc/systemd/system/node_exporter.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Prometheus nodejs | Restart node_exporter'
  when: 'ansible_service_mgr == "systemd"'

- name: 'Prometheus nodejs | Install | Copy the Node Exporter init.d script'
  ansible.builtin.template:
    src: 'node_exporter.j2'
    dest: '/etc/init.d/node_exporter'
    owner: 'root'
    group: 'root'
    mode: '0750'
  notify:
    - 'Prometheus nodejs | Restart node_exporter (init.d)'
  when: 'ansible_service_mgr != "systemd"'

- name: 'Prometheus nodejs | Install | Allow Node Exporter port in SELinux'
  community.general.seport:
    ports: '{{ node_exporter_web_listen_port }}'
    proto: 'tcp'
    setype: 'http_port_t'
    state: 'present'
  when:
    - 'ansible_version.full is version("2.4", ">=")'
    - 'ansible_selinux.status == "enabled"'
