---

- name: 'Prometheus nodejs | Set Facts | Gather required facts'
  ansible.builtin.setup:
    filter:
      - 'ansible_service_mgr'
      - 'ansible_architecture'
      - 'ansible_selinux'
      - 'ansible_os_family'

- name: 'Prometheus nodejs | Set Facts | Fail on unsupported init systems'
  ansible.builtin.debug:
    msg: 'Using init.d script, not a systemd OS'
  when: 'ansible_service_mgr != "systemd"'

- name: 'Prometheus nodejs | Set Facts | Check collectors'
  ansible.builtin.fail:
    msg: 'Collector cannot be both disabled and enabled'
  loop: '{{ node_exporter_disabled_collectors }}'
  when: 'item in node_exporter_enabled_collectors'

- name: 'Prometheus nodejs | Set Facts | Include main variables'
  ansible.builtin.include_vars:
    file: 'main.yml'
    name: 'node_exporter_common'

- name: 'Prometheus nodejs | Set Facts | Gather OS specific variables'
  ansible.builtin.include_vars:
    dir: '{{ item }}'
    name: 'node_exporter_custom'
  with_first_found:
    - '{{ ansible_os_family | lower }}/{{ ansible_distribution_major_version }}'
    - '{{ ansible_os_family | lower }}'
    - 'default.yml'

- name: 'Prometheus nodejs | Set Facts | Set architecture variable'
  ansible.builtin.set_fact:
    node_exporter_arch: >-
      {{ node_exporter_common.go_arch_map[ansible_architecture] |
      default(ansible_architecture) }}

- name: 'Prometheus nodejs | Set Facts | Set all required facts'
  ansible.builtin.set_fact:
    node_exporter_sha_url: '{{ node_exporter_common.base_url }}/sha256sums.txt'
    node_exporter_tar_url: >-
      {{ node_exporter_common.base_url }}/node_exporter-{{
        node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz
