---

node_exporter_disabled_collectors: []
node_exporter_enabled_collectors:
  - systemd:
      unit-exclude: '^(.+\.(socket|scope|target))|((-|acpid|apt-|atd|atop|basic|blk-|boot|blockdev|dev-|dbus|emerg|console-|cloud-|crypt|dm-|e2scrub_|first-boot|graphical|getty|kmod|man-db|modprobe|multi-user|network|nss|quemu|slices|sockets|serial|shutdown|swap|rpc|sys|snap|lvm2|user|umount).*)$'  # yamllint disable-line rule:line-length  - filesystem:
  - filesystem:
      mount-points-exclude: '^(sys|proc|auto|rpc_pipe|tmp)fs$'
      fs-types-exclude: '^/(sys|proc|dev|boot)($|/)'
node_exporter_service_enabled: true
node_exporter_force_install: false
node_exporter_service_name: 'node_exporter'
node_exporter_service_state: 'started'
node_exporter_system_group: 'node-exp'
node_exporter_system_user: 'node-exp'
node_exporter_textfile_dir: ''
node_exporter_version: '1.6.0'
node_exporter_web_listen_address: '0.0.0.0'
node_exporter_web_listen_port: 9100
node_exporter_consul_integration: false
