---

- name: 'Docker | Apt | Install dependencies'
  ansible.builtin.apt:
    name: '{{ dependencies }}'
    state: 'present'
    force_apt_get: true
    update_cache: true

- name: 'Docker | Apt | Add Apt key from the official Docker repo'
  ansible.builtin.apt_key:
    url: '{{ docker_key }}'
    state: 'present'

- name: 'Docker | Apt | Add Docker official repository'
  ansible.builtin.apt_repository:
    repo: '{{ docker_repo }}'
    state: 'present'
    update_cache: true

- name: 'Docker | Apt | Install Docker'
  ansible.builtin.apt:
    name:
      - 'docker-ce={{ docker_version }}'
      - 'docker-compose-plugin'
    state: 'present'
    allow_downgrade: true
