---

- name: 'Verify'
  hosts: 'all'
  gather_facts: false

  tasks:
    - name: 'Get VMagent systemd service'
      ansible.builtin.systemd:
        name: 'vmagent'
      register: __vmagent

    - name: 'Check VMagent systemd service state'
      ansible.builtin.assert:
        that: '__vmagent.status.ActiveState == "active"'

    - name: 'Check VMagent systemd service enabled'
      ansible.builtin.assert:
        that: '__vmagent.status.UnitFileState == "enabled"'

    - name: 'Get VMagent targets, check vmagent job health'
      ansible.builtin.uri:
        url: 'http://localhost:8429/api/v1/targets'
        return_content: true
      retries: 10
      delay: 6
      until: |
        "success" == __targets.json.status
        and
        "up" == (__targets.json.data.activeTargets | selectattr("discoveredLabels.job", "match", "vmagent") | first).health
      register: '__targets'

    - name: 'Get vmagent job target'
      ansible.builtin.set_fact:
        __vmagent_job: '{{ __targets.json.data.activeTargets | selectattr("discoveredLabels.job", "match", "vmagent") | first }}'

    - name: 'Check vmagent job target'
      ansible.builtin.assert:
        that:
          - '__vmagent_job.labels.job == "vmagent"'
          - '__vmagent_job.labels.service == "monitoring"'
        success_msg: 'vmagent job is OK'
