---

- name: 'Prometheus Samba | Consul integration | Get service facts'
  ansible.builtin.service_facts:
  become: true

- name: 'Prometheus Samba | Consul integration | Add Samba exporter consul hcl'
  ansible.builtin.copy:
    src: 'files/samba-exporter.hcl'
    dest: '/etc/consul.d/samba-exporter.hcl'
    owner: '{{ prometheus_samba_exporter_consul_user }}'
    group: '{{ prometheus_samba_exporter_consul_group }}'
    mode: '0400'
  become: true
  notify:
    - 'Prometheus Samba | Reload consul config'
  when:
    - 'ansible_facts.services["consul.service"] is defined'
