---

- name: 'Prometheus mysql | Linux | Restart mysqld exporter'
  ansible.builtin.systemd:
    daemon_reload: true
    name: '{{ prometheus_mysqld_exporter_service_name }}'
    state: 'restarted'
  when: 'prometheus_mysqld_exporter_service_state != "stopped"'
  become: true

- name: 'Prometheus mysql | Windows | Restart win mysqld exporter'
  ansible.windows.win_service:
    name: '{{ prometheus_mysqld_exporter_win_service_name }}'
    state: 'restarted'
